name: CoreAuth
main: pl.grzegorz2047.bukkitpe.core.CoreAuth
api: 1.0.0
version: 1.0.0
author: grzegorz2047
commands:
 login:
  description: login command
  default: true
 register:
  description: register command
  default: true
 changepassword:
  description: changepassword command
  default: true